name: Periodic health check


on:
  push:
    branches:
      - master
    schedule:
      # * is a special character in YAML so you have to quote this string
      - cron:  '*/1 * * * *'

jobs:
  simple_periodic_health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL/health
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://fullstack-part11.herokuapp.com/health
          follow-redirect: no # Optional, defaults to "no"
          # Fail this action after this many failed attempts
          max-attempts: 3 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
